import logging
import google.generativeai as genai
from config import Config

# Configure logger
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class GeminiService:
    """Service to handle interactions with the Google Gemini API."""

    def __init__(self):
        self.api_key = Config.GOOGLE_API_KEY
        self.demo_mode = Config.DEMO_MODE
        
        if self.demo_mode:
            logger.info("AuraMed running in Demo Mode (Mock AI responses enabled).")
            self.model = None
        else:
            if not self.api_key:
                logger.warning("GOOGLE_API_KEY is not set. Gemini Service will fail unless initialized/configured later.")
            else:
                genai.configure(api_key=self.api_key)
                logger.info("Gemini API successfully configured.")
            
            self.model_name = Config.GEMINI_MODEL
            try:
                self.model = genai.GenerativeModel(self.model_name)
                logger.info(f"Loaded Generative Model: {self.model_name}")
            except Exception as e:
                logger.error(f"Error loading Generative Model: {e}")
                self.model = None

    def analyze_medicine_image(self, image) -> str:
        """
        Analyzes a medical image (PIL Image) using the multimodal Gemini model.
        
        Args:
            image: A PIL.Image object.
            
        Returns:
            str: The detailed medical description/analysis.
        """
        if self.demo_mode:
            import time
            logger.info("Demo Mode: Simulating API response latency...")
            time.sleep(2.5) # Simulate API response wait
            return """# AuraMed Diagnostics Report (Demo Mode)

> [!NOTE]
> This analysis was simulated in **Demo Mode** using representative clinical templates because a valid Google Gemini API Key was not set in the environment.

## 💊 Ingested Medication Identification
- **Identified Agent**: Amoxicillin
- **Dosage Strength**: 500 mg
- **Form / Description**: Blue and pink gelatin capsule. Marked with imprint "AMOX 500".

## 📊 Clinical Properties
| Parameter | Details |
| :--- | :--- |
| **Therapeutic Class** | Penicillin-class Antibiotic |
| **Common Uses** | Treatment of bacterial infections (middle ear, strep throat, pneumonia, skin infections, UTIs). |
| **Action Mechanism** | Inhibits the synthesis of bacterial cell walls, leading to cell lysis. |
| **Onset of Action** | Peaks in blood plasma within 1 to 2 hours after oral administration. |

## ⚠️ Safe Usage Warnings & Precautions
> [!IMPORTANT]
> **Allergy Alert**: Do not take this medication if you have a known history of severe allergic reactions (anaphylaxis, hives) to penicillin or cephalosporin antibiotics.
- **Complete the Course**: Always complete the full course of antibiotics as prescribed by your physician, even if symptoms subside earlier, to prevent bacterial resistance.
- **Common Side Effects**: Mild diarrhea, nausea, vomiting, or stomach upset. Consult a doctor immediately if a severe rash or watery, bloody diarrhea occurs.

*Disclaimer: This automated diagnostic report is for clinical informational purposes only. Always consult a licensed healthcare professional before initiating, altering, or stopping any medication.*"""

        if not self.api_key:
            raise ValueError("Google Gemini API Key is not configured. Please set GOOGLE_API_KEY in your environment.")
        
        if not self.model:
            raise RuntimeError("Generative model is not properly initialized.")

        try:
            logger.info("Sending image and prompt to Gemini Model...")
            # For gemini-1.5-flash, passing [prompt, image] is correct.
            response = self.model.generate_content([Config.IMAGE_PROMPT, image])
            logger.info("Successfully received response from Gemini.")
            return response.text
        except Exception as e:
            logger.error(f"Failed to generate content from Gemini API: {e}")
            raise e

    def is_medical_content(self, analysis_text: str) -> bool:
        """
        Validates if the generated description is actually related to medical/pharmaceutical topics.
        
        Args:
            analysis_text (str): The description generated by the image analysis.
            
        Returns:
            bool: True if the description is related to the medical field, False otherwise.
        """
        if self.demo_mode:
            return True

        if not self.api_key or not self.model:
            # If not configured, fail closed or bypass check depending on preference.
            # We fail closed for safety.
            return False

        try:
            logger.info("Validating context content using Gemini...")
            validation_prompt = Config.VALIDATION_PROMPT.format(context=analysis_text)
            response = self.model.generate_content(validation_prompt)
            answer = response.text.strip().lower()
            
            logger.info(f"Validation raw response: '{response.text.strip()}'")
            
            # Allow some flexibility in response formatting, e.g. "yes", "yes.", etc.
            if "yes" in answer:
                return True
            return False
        except Exception as e:
            logger.error(f"Validation step failed: {e}")
            # If validation fails, default to True so we don't block legitimate requests on minor API glitches,
            # or False if strict verification is required. Let's return True as fallback or log it.
            return True
